#!/bin/sh
# Let Rocket bind the PORT defined on our Dockerfile
export ROCKET_PORT="${PORT}"

# Do not use local storage
# TODO: Store rsa_key in db or env 
export ORG_ATTACHMENT_LIMIT=0
export USER_ATTACHMENT_LIMIT=0
#export DISABLE_ICON_DOWNLOAD=true
export ICON_CACHE_TTL=0
export ICON_CACHE_NEGTTL=0

if [ "${ENABLE_ADMIN}" == "true" ]; then
  echo "==> Enabling admin dashboard..."
  if [ "${ADMIN_TOKEN}" == "" ]; then
    echo "   No token found for the admin dashboard, unsetting..."
    unset ADMIN_TOKEN
  fi
else
  echo "==> Admin token not found, disabling admin panel..."
  unset ADMIN_TOKEN
fi

if [ -z "${RSA_CONTENT}" ]; then
  echo "==> RSA_CONTENT is missing, please see https://rtapp.tk/bwrs-rsa-content-env"
else
  echo "==> RSA_CONTENT found, attempting to decode..."
  echo "${RSA_CONTENT}" | base64 -d | tar zxf -
  export RSA_KEY_FILENAME=${PWD}/rsa_key
fi



/bin/sh /start.sh
